import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { Header } from '@/common/components/navigation/Header'

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={
          roboto.className + ' min-h-screen h-fit bg-light text-primary'
        }
      >
        <Header />
        <div className="flex justify-center py-8 px-10">{children}</div>
      </body>
    </html>
  )
}
