openapi: 3.0.0
info:
  title: Trust Registry
  version: 1.0.0
  description: '[http://localhost:3000/api/docs-json](http://localhost:3000/api/docs-json)'
paths:
  /health:
    get:
      description: Healthcheck endpoint
      responses:
        '200':
          description: OK
  /registry:
    get:
      description: Returns the whole registry
      responses:
        '200':
          description: OK
          content:
            text/json:
              schema:
                type: string
                example: >-
                  {}

components: {}
tags: []
