version: '3'

services:
  trust-registry:
    image: ${REGISTRY:-local}/ssi-trust-registry:${IMAGE_TAG:-latest}
    container_name: trust-registry
    ports:
      - 3000:3000
    command:
      - yarn
      - dev
    healthcheck:
      test: curl -f http://localhost:3000/health
      interval: 15s
      timeout: 5s
    environment:
      URL: http://0.0.0.0
      PORT: 3000
      DB_CONNECTION_STRING: mongodb://mongo:mongo@mongo:27017
      DB_NAME: trust-registry
    networks:
      - ssi-trust-registry
    depends_on:
      mongo:
        condition: service_healthy
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: trust-registry
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 15s
      timeout: 5s
      start_period: 5s
    networks:
      - ssi-trust-registry
    volumes:
      - mongo:/data/db
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - ssi-trust-registry
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo:

networks:
  ssi-trust-registry:
