{{- range $key, $_ := .Values.ingress }}
{{- if eq (tpl (toString .enabled) $) "true" }}
{{- if $key }}
---
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- if .name }}
  name: {{ tpl .name $ }}
  {{- else }}
  name: {{ printf "%s-%s" (include "trust-registry.fullname" $) $key }}
  {{- end }}
  {{- with .namespace }}
  namespace: {{ tpl . $ }}
  {{- end }}
  labels:
    {{- include "trust-registry.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .tls }}
  tls:
  {{- range .tls }}
    - hosts:
      {{- range .hosts }}
        - {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | quote }}
      {{- end }}
      secretName: {{ include "common.tplvalues.render" ( dict "value" .secretName "context" $ ) }}
  {{- end }}
{{- end }}
  ingressClassName: {{ .className }}
  rules:
  {{- range $rules := .hosts }}
    - host: {{ tpl $rules.host $ | quote }}
      http:
        paths:
      {{- if not $rules.paths }}
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "trust-registry.fullname" $ }}
              port:
                number: {{ $.Values.service.port }}
      {{- else }}
        {{- range $paths := $rules.paths }}
        {{- if $paths.path }}
        - path: {{ tpl $paths.path $ }}
        {{- else }}
        - path: /
        {{- end }}
          pathType: {{ default "Prefix" $paths.pathType }}
          backend:
            service:
              name: {{ include "trust-registry.fullname" $ }}
              port:
                number: {{ $.Values.service.port }}
        {{- end -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
