apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trust-registry.fullname" . }}
  labels:
    {{- include "trust-registry.labels" . | nindent 4 }}
stringData:
  {{- range $k,$v := .Values.config }}
  {{ upper (snakecase $k) }}: {{ tpl (toString .) $ | quote }}
  {{- end }}
