apiVersion: v1
kind: Service
metadata:
  name: {{ include "trust-registry.fullname" . }}
  labels:
    {{- include "trust-registry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: frontend
      port: {{ .Values.service.frontend.port }}
      targetPort: {{ default .Values.service.frontend.port .Values.service.frontend.targetPort }}
      protocol: {{ default "TCP" .Values.service.frontend.protocol }}
    - name: backend
      port: {{ .Values.service.backend.port }}
      targetPort: {{ default .Values.service.backend.port .Values.service.backend.targetPort }}
      protocol: {{ default "TCP" .Values.service.backend.protocol }}
  selector:
    {{- include "trust-registry.selectorLabels" . | nindent 4 }}
