environments:
  dev:
    values:
      - namespace: trust-registry-dev
  prod:
    values:
      - namespace: trust-registry-prod
---
repositories:
- name: bitnami
  url: oci://registry-1.docker.io/bitnamicharts
  oci: true
---
releases:
- name: trust-registry
  namespace: {{ .Values.namespace }}
  chart: ./trust-registry
  values:
    - ./trust-registry/conf/{{ .Environment.Name }}/values.yaml
---
helmDefaults:
  timeout: 300
  wait: true
  atomic: true
  cleanupOnFail: true
  createNamespace: false
