name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      PORT: 3000
      URL: http://localhost
      DB_CONNECTION_STRING: mongodb://localhost:4000
      DB_NAME: test_registry
    services:
      mongo:
        image: mongo:6.0
        ports:
          - 4000:27017

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test

  build:
    name: Build and push
    needs: test
    permissions:
      packages: write
    runs-on: ubuntu-latest

    # Don't build dependabot, don't build PRs
    if: ${{ github.triggering_actor != 'dependabot[bot]' && github.event_name != 'pull_request' }}

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/ssi-trust-registry
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=sha,prefix={{branch}}-,priority=601
            type=ref,event=branch,priority=600
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
