name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy to EKS
    concurrency:
      group: dev
      cancel-in-progress: false
    environment:
      name: dev
      url: ${{ vars.PUBLIC_URL }}
    permissions:
      id-token: write
      contents: read
      checks: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: mdgreenwald/mozilla-sops-action@v1.4.1
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: af-south-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-cicd
      - uses: unfor19/install-aws-cli-action@v1
      - run: aws eks update-kubeconfig --name ${{ secrets.CLUSTER }}
      - uses: azure/setup-kubectl@v3
      - uses: azure/setup-helm@v3
        with:
          version: v3.12.2
      - uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: 1.46.1

      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/ssi-trust-registry
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=sha,prefix={{branch}}-,priority=601
            type=ref,event=branch,priority=600
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Helmfile Diff
        uses: helmfile/helmfile-action@v1.1.0 # https://github.com/helmfile/helmfile-action
        with:
          helmfile-args: |
            diff \
              --environment ${{ vars.ENVIRONMENT }} \
              -f ./helm/trust-registry.yaml \
              --set image.tag=${{ env.IMAGE_TAG }}
          helm-plugins: |
            https://github.com/databus23/helm-diff
          helmfile-version: v0.155.1
          helm-version: v3.12.2
        env:
          IMAGE_TAG: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
      - name: Wait for CI
        if: github.event_name != 'workflow_dispatch'
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.sha }}
          running-workflow-name: 'Deploy to EKS'
          repo-token: ${{ github.token }}
          wait-interval: 10
      - name: Helmfile Apply
        uses: helmfile/helmfile-action@v1.1.0
        with:
          helmfile-args: |
            apply \
              --environment ${{ vars.ENVIRONMENT }} \
              -f ./helm/trust-registry.yaml \
              --set image.tag=${{ env.IMAGE_TAG }} \
              --skip-deps
          helmfile-version: v0.155.1
          helm-version: v3.12.2
        env:
          IMAGE_TAG: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}

      - name: Test Health
        run: curl --silent --show-error --fail ${{ vars.PUBLIC_URL }}/health
      - name: Test Registry
        run: curl --silent --show-error --fail ${{ vars.PUBLIC_URL }}/api/registry
